language: scala
jdk:
  - oraclejdk8
scala:
   - 2.11.7
branches:
  only:
    - master
script:
    - cd sss.asado-common ; sbt clean test publish
    - cd ../sss.asado-network ; sbt clean test publish
    - cd ../sss.asado-ledger ; sbt clean test publish
    - cd ../sss.asado-node ; sbt clean test publish
    - cd ../sss.asado-nobu ; sbt clean test 
